### PR TITLE
feat: fix logo & wordmark

### PR DESCRIPTION
**Pull request by kazimmt**
Use Direct Logo.
Convert Wordmark text to Shape.
Add `ai` project file
Closes:
- https://github.com/revanced/revanced-branding/issues/2
- https://github.com/revanced/revanced-branding/issues/3
- https://github.com/revanced/revanced-branding/issues/4

### CODE REVIEW

**Comment by xafn** [comment]
Considering these are all vector images, I don't think we need a `.psd` file.

**Comment by oSumAtrIX** [comment]
Yeah, only `.ai` would be fine.

**Comment by kazimmt** [comment]
> Yeah, only `.ai` would be fine.

Ok, then can you please forcedly remove `psd` file's commit.

**Comment by oSumAtrIX** [comment]
The `.afdesign` files should be removed in favor of the `.ai` files.

**Comment by oSumAtrIX** [comment]
The project structure in the `.ai` files is messed up:

image

Additionally, the wordmark font in `.afdesign` has been converted to shapes, which shouldn't have been. All in all the PR is a bit messed up. Closing for that reason. If you intend to fix the issues consider the following:

The `.ai` project files should __replace__ the `.afdesign` files and __retain__ the project structure fully. The renders __have__ to be generated from the new `.ai` project file.

**Pull request closed without merging**
