### PR TITLE
Update revanced-logo-shape.svg

### PR DESCRIPTION
**Pull request by xafn**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Why was the margin removed? All the other variations still have the margin.

**Comment by xafn** [comment]
Because it's just the shape SVG, people would want it without the margins. And, no, the other files do not have a margin around the entire logo.

**Comment by oSumAtrIX** [comment]
> And, no, the other files do not have a margin around the logo.

The margin exists around the shape.

Currently, every variation only toggles layers on or off or changes colors keeping the proportions and sizes for each variation correct. The shape and its margin are considered part of the logo and removing the margin is the same as altering the logo.

**Comment by Ushie** [comment]
The margin makes it difficult to use the logo shape in some situations, such as an icon in a navigation bar or such, it either looks smaller than it should be or it would push the things around it and make the container bigger just to look the size it should be

**Comment by Ushie** [comment]
I see no situation where we would need margin to already be included in the shape SVG, if we were to need margin, we would use it willingly, the included margin can't be excluded without editing the SVG file

**Pull request merged**
